# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
    command = "npm run build"
    publish = "out"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[context.production.environment]
    NEXT_SERVERLESS = "true"
    NODE_ENV = "production"
